<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5050" started-at="2015-04-08T12:19:39Z" finished-at="2015-04-08T12:19:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5050" started-at="2015-04-08T12:19:39Z" finished-at="2015-04-08T12:19:44Z">
      <class name="com.testng.demo.TestTimeout">
        <test-method status="FAIL" signature="testThisShouldFail()[pri:0, instance:com.testng.demo.TestTimeout@6866da50]" name="testThisShouldFail" duration-ms="1021" started-at="2015-04-08T22:19:39Z" finished-at="2015-04-08T22:19:40Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method org.testng.internal.TestNGMethod.testThisShouldFail() didn't finish within the time-out 1000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testThisShouldFail() didn't finish within the time-out 1000
	at com.testng.demo.TestTimeout.testThisShouldFail(TestTimeout.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThisShouldFail -->
        <test-method status="PASS" signature="testThisShouldPass()[pri:0, instance:com.testng.demo.TestTimeout@6866da50]" name="testThisShouldPass" duration-ms="4002" started-at="2015-04-08T22:19:40Z" finished-at="2015-04-08T22:19:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThisShouldPass -->
      </class> <!-- com.testng.demo.TestTimeout -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
